### ISSUE TITLE
Question about coordinate system

### ISSUE THREAD

**Issue by ONMEKEEP** [NeBula-Autonomy/nebula-odometry-dataset#11]
Hello. I have some questions about the coordinate system.
If possible, I hope you can provide a clearer and more detailed explanation.

1. What does the frame_id "arch" stand for？
2. How to get the transformation from velodyne to base_link?

**Comment by femust** [comment]
1. Arch is a fixed physical thing that the sensors are attached to (the black thing), it has a reference system.
![image](https://user-images.githubusercontent.com/26916586/186355317-9ed2d69e-cec4-4835-a265-8d83de492162.png)
2. Chain of transformations, this is the thing that you are looking for. arch <-> base_link is fixed (constant in time), just translation vector, you can assume just identity in most cases (depending on how you compare to the ground truth). In any case, you can use also the loading procedure from [robot_description in locus](https://github.com/NeBula-Autonomy/LOCUS/blob/main/sensor_description/urdf/robot_description.urdf.xacro#L8). There, we show how we load all params from yaml file.

**Comment by ONMEKEEP** [comment]
> 

Thanks a lot.  What you have described is helpful to me.

**Comment by femust** [comment]
ok closing then :) have fun
