### ISSUE TITLE
lidar bag and imu bag were not recorded on one day?

### ISSUE THREAD

**Issue by Guo-lf** [NeBula-Autonomy/nebula-odometry-dataset#6]
When I was using lidar dataset 'D',I finded that the bags named 'husky4_lidar_2019-08-20-xxxx.bag' were recorded on Aug 21 2019,while the bag named 'imu.bag' was recorded on Aug 22 2019.those two kinds of sensor massege were not recorded on one day.It's there something wrong?  thank you!
------------------------------------------------------------------
path:         husky4_lidar_2019-08-20-13-33-22_61.bag
version:      2.0
duration:     26.9s
start:        Aug 21 2019 04:33:22.45 (1566333202.45)
end:          Aug 21 2019 04:33:49.30 (1566333229.30)
------------------------------------------------------------------
path:        imu.bag
version:     2.0
duration:    1hr 25:42s (5142s)
start:       Aug 22 2019 03:24:20.01 (1566415460.01)
end:         Aug 22 2019 04:50:02.02 (1566420602.02)

**Comment by ONMEKEEP** [comment]
I found the same problem. How did this problem be solved?
