### ISSUE TITLE
about the extrinsicRot and imu noise

### ISSUE THREAD

**Issue by Guo-lf** [NeBula-Autonomy/nebula-odometry-dataset#8]
Thanks for your great work！I have some question！  I am running dataset D and F using lio-sam for comparasion,but I can not set the params well. would you mind telling me how to set the parameter I list below.
=========================================================
  imuAccNoise: 
  imuGyrNoise: 
  imuAccBiasN: 
  imuGyrBiasN: 
  imuGravity: 
  imuRPYWeight: 
  Extrinsics: T_lb (lidar -> imu)
  extrinsicTrans: [                  ]
  extrinsicRot: [                ]
  extrinsicRPY: [                  ]

                 I tried so hard to set it,but failed!Thanks again！

**Comment by femust** [comment]
@Guo-lf  for imu we use [VN100](https://www.vectornav.com/products/detail/vn-100?gclid=Cj0KCQjwxtSSBhDYARIsAEn0thQy4ZSoNNRcvUZzJBFEtlZtiIb9PiUJty0BAxZwOUEK2bK6l9XtnLIaAtTnEALw_wcB) so probably it's worth to explore the manual/documentation unless @BenjaminMorrell or @LossOfHumanIdentity  have written down these parameters one day?
