### ISSUE TITLE
Why can't datasets be downloaded？

### ISSUE THREAD

**Issue by ONMEKEEP** [NeBula-Autonomy/nebula-odometry-dataset#9]
When I click the download link, there are some error prompts like below？
------
This can usually be fixed by giving the web server write access to the root directory. See https://docs.nextcloud.com/server/24/go.php?to=admin-dir_permissions
------
What do I need to do?
Look forward to your reply!

**Comment by femust** [comment]
Hey @ONMEKEEP  thanks for the interest in our datasets! Can you tell me which dataset you are trying to download?

**Comment by ONMEKEEP** [comment]
> Hey @ONMEKEEP thanks for the interest in our datasets! Can you tell me which dataset you are trying to download?

Thank you for your reply. I want to download all LiDAR datasets collected by Husky.

**Comment by femust** [comment]
can you give me the letter? (A,C,D,F,G,J,N,O) or do you experience this for every dataset this issue?

**Comment by ONMEKEEP** [comment]
> can you give me the letter? (A,C,D,F,G,J,N,O) or do you experience this for every dataset this issue?

Yes, all dataset links experience the same problem. A, C, D, F, G, J, N, O are what I need.

**Comment by femust** [comment]
Oh... I see @BenjaminMorrell  can you look at what's going on?

**Comment by 18713472531** [comment]
> Oh... I see @BenjaminMorrell can you look at what's going on?

I got the same problem and the same error prompts for all the datasets, it seems that you didn't provide permissions, can you fix this?

**Comment by femust** [comment]
Hey, currently we're having some problems with nextcloud where we store datasets, we're working on migrating to the other server

**Comment by 18713472531** [comment]
> 

thanks

**Comment by femust** [comment]
@18713472531 A,B,C,D,E,F is up

**Comment by saberpoi** [comment]
It seems that all the 'extra file' got the same problem. Could you please solve this problem?

**Comment by femust** [comment]
@saberpoi for A-J extra I'm updating right now, they should be available in 5h fully.

**Comment by saberpoi** [comment]
> @saberpoi for A-J extra I'm updating right now, they should be available in 5h fully.

thanks a lot!!

**Comment by femust** [comment]
@saberpoi  and @18713472531 the main dataset is mostly updated, probably the main dataset should be available end of August. Enjoy!

Hovermap dataset most likely will come by the end of September,
